import type { QuizScenarioConfig } from "../types/quiz";
import { heartSymbols } from "./heartSymbols";

export const quizScenario: QuizScenarioConfig = {
  ui: {
    soundToggle: {
      onLabel: "Вимкнути звук",
      offLabel: "Увімкнути звук",
    },
    stageTransitionDelayMs: 440,
    progress: {
      ariaLabel: "Прогрес квізу",
      stageLabel: "Етап",
    },
  },
  home: {
    badge: "Міні-гра",
    unlockGate: {
      enabled: true,
      code: "14022026",
      codeLength: 8,
      tagLabel: "код кохання",
      codeInputLabel: "Введи 8-значний схований код",
      codeInputPlaceholder: "________",
      successMessage: "Ти молодець!",
      successDelayMs: 650,
    },
    title: "Подарунок для\u00A0найкоханішої",
    subtitle: "10 маленьких кроків до сюрпризу, який зроблений саме для тебе",
    startButton: "Почати нашу історію",
    startButtonPulse: true,
  },
  final: {
    badge: "Фінал",
    title: `Ти відкрила всі 10 сердець ${heartSymbols.primary}`,
    message:
      "Дякую, що ти є в моєму житті. Ти робиш мої дні теплішими, а мене кращим. Я дуже тебе кохаю.",
    rewardButton: "Відкрити подарунок",
    rewardLine1:
      "Нагорода: купон на ідеальне побачення + 1000 обіймів без обмежень.",
    rewardLine2: "Промокод: LOVE-FOREVER",
  },
  stages: [
    {
      id: 1,
      kind: "choice",
      title: "Етап 1",
      prompt: "Хто ти для мене?",
      options: [
        { id: "bun", label: "Моя булочка" },
        { id: "air", label: "Моє повітря" },
        { id: "universe", label: "Мій всесвіт" },
      ],
      rules: {
        type: "correct_option",
        correctOptionId: "universe",
        incorrectMessage: `Це також, але спробуй ще раз ${heartSymbols.primary}`,
      },
      rewardLabel: "Серце щирості",
    },
    {
      id: 2,
      kind: "choice",
      title: "Етап 2",
      prompt:
        "Якби можна було обрати щось одне і це тривало б вічність, що б ти обрала?",
      options: [
        { id: "walk", label: "Прогулянка" },
        { id: "talk", label: "Розмова" },
        { id: "hug", label: "Обійми" },
        { id: "meet", label: "Поцілунок" },
      ],
      rules: {
        type: "any",
      },
      rewardLabel: "Серце спогадів",
    },
    {
      id: 3,
      kind: "truth",
      title: "Етап 3",
      prompt: "Правда чи неправда?",
      statement: "Я люблю тебе все більше з кожним днем",
      trueButtonLabel: "Правда",
      falseButtonLabel: "Неправда (але мило)",
      rules: {
        type: "correct_answer",
        correctAnswer: "truth",
        incorrectMessage: `Це щира правда, в тебе є ще змога обрати правильну відповідь ${heartSymbols.primary}`,
      },
      rewardLabel: "Серце чесності",
    },
    {
      id: 4,
      kind: "catch",
      title: "Етап 4",
      prompt: "Злови усі сердечка за 10 секунд!",
      rules: {
        target: 10,
        durationSec: 10,
        allowRetryAfterTimeout: true,
        timeoutPraiseText:
          "Час вийшов, але ти молодець! Спробуй знову зібрати всі ті частинки мого серця, що я тобі дарую 🥰",
        retryButtonLabel: "Спробувати ще раз",
        successText: `Ти спіймала усі частинки мого серця! Ти\u00A0неймовірна ${heartSymbols.primary}`,
        continueButtonLabel: "Далі",
        retryAfterSuccessButtonLabel: "Спробувати ще раз",
        minSpawnDistancePercent: 34,
        spawnArea: {
          minX: 8,
          maxX: 92,
          minY: 10,
          maxY: 88,
        },
      },
      scoreLabel: "Спіймано",
      timeLabel: "Таймер",
      secondsSuffix: "с",
      heartAriaLabel: "Спіймати сердечко",
      rewardLabel: "Серце драйву",
    },
    {
      id: 5,
      kind: "reaction",
      title: "Етап 5",
      prompt: "Зупини сердечко в зоні кохання",
      rules: {
        cycleDurationMs: 1500,
        sweetSpotStart: 45,
        sweetSpotEnd: 55,
        successDelayMs: 380,
        meterLabel: "Спіймай момент і натисни точно в рожеву зону",
        actionButtonLabel: "Зловити момент",
        idleMessage: `Тайминг вирішує все: дочекайся ідеального моменту ${heartSymbols.primary}`,
        failMessage: "Ледь-ледь! Ще одна спроба ідеального таймінгу.",
        successMessage: "Ідеально! Ти зловила цей момент ✨",
      },
      rewardLabel: "Серце моменту",
    },
    {
      id: 6,
      kind: "memory",
      title: "Етап 6",
      prompt: "Знайди всі пари наших моментів",
      rules: {
        cards: [
          { id: "hug", label: "Обійми" },
          { id: "kiss", label: "Поцілунок" },
          { id: "smile", label: "Усмішка" },
        ],
        flipBackDelayMs: 520,
        matchedLabel: "Знайдено",
        successMessage: "Ідеально! Ти відкрила всі пари ✨",
        continueButtonLabel: "Далі",
        retryButtonLabel: "Спробувати ще раз",
      },
      rewardLabel: "Серце памʼяті",
    },
    {
      id: 7,
      kind: "puzzle",
      title: "Етап 7",
      prompt: "Збери речення у правильному порядку",
      words: ["спокій", "шуму", "мій", "ти", "серед"],
      previewPlaceholder: "...",
      rules: {
        acceptedPhrases: ["ти мій спокій серед шуму"],
        normalize: "trim_lower",
        incorrectMessage: `Трохи інакше, але мені все одно подобається твій варіант ${heartSymbols.primary}`,
        continueButtonLabel: "Далі",
        retryButtonLabel: "Спробувати ще раз",
      },
      rewardLabel: "Серце слів",
    },
    {
      id: 8,
      kind: "tic_tac_toe",
      title: "Етап 8",
      prompt: "Збери 3 сердечка в одну лінію",
      rules: {
        playerSymbol: heartSymbols.primary,
        botSymbol: heartSymbols.secondary,
        botSkill: 0.72,
        winMessage: `Перемога! Ти зібрала ідеальну лінію ${heartSymbols.primary}`,
        loseMessage: "Цього разу не вийшло, давай разок?",
        drawMessage: "Нічия! Ще раунд для красивої перемоги?",
        retryButtonLabel: "Спробувати ще раз",
        continueButtonLabel: "Далі",
      },
      rewardLabel: "Серце гри",
    },
    {
      id: 9,
      kind: "hold",
      title: "Етап 9",
      prompt: "Чим дужче тримаєш, тим більше сила кохання",
      rules: {
        holdDurationMs: 2600,
        progressLabel: "Сила кохання",
        resetHint: `Майже! Спробуй ще раз і потримай трохи довше ${heartSymbols.primary}`,
        successMessage: "Ти зробила це ідеально!",
        buttonIdleLabel: "Тримай мене",
        buttonHoldingLabel: "Ще трішки...",
        buttonSuccessLabel: "100% сили кохання!",
      },
      rewardLabel: "Серце ритму",
    },
    {
      id: 10,
      kind: "choice",
      title: "Етап 10",
      prompt: "Готова до фінального сюрпризу?",
      options: [
        { id: "yes-very", label: "Так, дуже" },
        { id: "yes-of-course", label: "Так, звісно" },
        { id: "already-waiting", label: "Ще довго чекати?" },
      ],
      rules: {
        type: "any",
      },
      rewardLabel: "Серце очікування",
    },
  ],
};
